// File generated by FlutterFire CLI — from web .env.local keys
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWp97dqAlYM6nqh3nEsEv9_ODAPnIouk',
    authDomain: 'simplify-systems-feefb.firebaseapp.com',
    projectId: 'simplify-systems-feefb',
    storageBucket: 'simplify-systems-feefb.firebasestorage.app',
    messagingSenderId: '357565939872',
    appId: '1:357565939872:web:5d1538b96ff68503bf89c5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJ0-V5Q0thTPpbCqleRg7s9OpxNjTKtc',
    authDomain: 'simplify-systems-feefb.firebaseapp.com',
    projectId: 'simplify-systems-feefb',
    storageBucket: 'simplify-systems-feefb.firebasestorage.app',
    messagingSenderId: '357565939872',
    appId: '1:357565939872:android:87804c4aa774882ebf89c5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWp97dqAlYM6nqh3nEsEv9_ODAPnIouk',
    authDomain: 'simplify-systems-feefb.firebaseapp.com',
    projectId: 'simplify-systems-feefb',
    storageBucket: 'simplify-systems-feefb.firebasestorage.app',
    messagingSenderId: '357565939872',
    appId: '1:357565939872:web:5d1538b96ff68503bf89c5',
    iosClientId: '',
    iosBundleId: 'com.simplifysystems.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgWp97dqAlYM6nqh3nEsEv9_ODAPnIouk',
    authDomain: 'simplify-systems-feefb.firebaseapp.com',
    projectId: 'simplify-systems-feefb',
    storageBucket: 'simplify-systems-feefb.firebasestorage.app',
    messagingSenderId: '357565939872',
    appId: '1:357565939872:web:5d1538b96ff68503bf89c5',
    iosClientId: '',
    iosBundleId: 'com.simplifysystems.app',
  );
}
